version: '3'

services:
  soft-arq-front:
    build: .
    container_name: arq-soft-front
    ports:
      - "4173:4173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host
